### ISSUE TITLE
Subscribe choice is no longer shown when using plugin CSS.

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/mailchimp-for-wordpress#174]
Because of this line.

```css
.mc4wp-form input[name^="_mc4wp_"] {
    display: none !important;
}
```
